sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"

cache:
  directories:
    - ~/.npm
os:
  - windows
  - linux
matrix:
  include:
    - node_js: "8"
      env: JOB_PART=lint
      os: linux
    - node_js: "10"
      env: JOB_PART=lint
      os: linux
    - node_js: "stable"
      env: JOB_PART=lint
      os: linux
    - node_js: "8"
      env: JOB_PART=integration
      os: linux
    - node_js: "10"
      env: JOB_PART=integration
      os: linux
    - node_js: "stable"
      env: JOB_PART=integration
      os: linux
    - node_js: "8"
      env: JOB_PART=integration
      os: windows
    - node_js: "10"
      env: JOB_PART=integration
      os: windows
    - node_js: "stable"
      env: JOB_PART=integration
      os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'windows' && `node -v` = v6* ]]; then 
      node `npm prefix -g`/node_modules/npm/bin/npm-cli.js i -g npm@latest;
    fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      npm i -g npm@latest;
    fi

install:
  - travis_wait npm ci
  - npm install -g codecov
  - npm install -g eslint

jobs:
  include:
    - stage: commit lint
      script: commitlint-travis
      os: linux
